Arrays
Janis-Kvs/c-sharp-syllabus_ pull request #5
Opened 2021-07-16 09:52 UTC by Janis-Kvs

Arrays all 8 exercises done

2021-07-17 09:36 UTC, ausmoons commented on csharp-basics/exercises/Arrays/Arrays/Exercise8/Program.cs
> +        private static Random random = new Random();
Private naming sākas ar "_" - > _random

2021-07-17 09:38 UTC, ausmoons requested changes

2021-07-17 09:38 UTC, ausmoons commented on csharp-basics/exercises/Arrays/Arrays/Exercise8/Program.cs
> +            if (String.Concat(guessingWord) == randomWord)
Te var uzreiz return

2021-07-17 09:38 UTC, ausmoons commented on csharp-basics/exercises/Arrays/Arrays/TicTacToe/Program.cs
> +                }
Pēc} jauna rinda

2021-07-17 09:38 UTC, ausmoons commented on csharp-basics/exercises/Arrays/Arrays/TicTacToe/Program.cs
> +                tie = true;
Tukša rinda pēc} un ieliec {}

2021-07-17 11:07 UTC, Janis-Kvs commented on csharp-basics/exercises/Arrays/Arrays/Exercise8/Program.cs
> +        private static Random random = new Random();
Done

2021-07-17 11:07 UTC, Janis-Kvs commented on csharp-basics/exercises/Arrays/Arrays/Exercise8/Program.cs
> +            if (String.Concat(guessingWord) == randomWord)
Done

2021-07-17 11:08 UTC, Janis-Kvs commented on csharp-basics/exercises/Arrays/Arrays/TicTacToe/Program.cs
> +                }
Done

2021-07-17 11:08 UTC, Janis-Kvs commented on csharp-basics/exercises/Arrays/Arrays/TicTacToe/Program.cs
> +                tie = true;
Done

2021-07-18 08:22 UTC, ausmoons approved these changes

2021-07-18 16:34 UTC, merged